### ISSUE TITLE
Hi Andrew

### ISSUE THREAD

**Issue by emveeoh** [andrewpuch/wordpress_4_1_1#2]
I found your video on YouTube and can't thank you enough for explaining the setup/install process so throughly. 

Here we are, 2+ years later, and I was wondering if any of your software choices or setup instructions have changed.

I'm going to attempt this setup on Monday and would appreciate any tips/updates that you might have. 

Thanks again for such a great tut!
MVO

**Comment by andrewpuch** [comment]
Hey Michael! I can't believe that video has been out for 2 years lol it's definitely still relevant but with tools like Docker and Terraform it could be a bit more cleaner. If you'd like to chat jump into the slack channel and we can talk more about your setup!

https://awstutorialseries.com - Left hand side request invite. 

Cheers!
